# Generated by Django 3.2 on 2021-11-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20211103_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchplayer',
            name='imp',
            field=models.SmallIntegerField(),
        ),
    ]
