# Generated by Django 3.2 on 2021-11-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_alter_match_avg_imp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='avg_imp',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='imp',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
