# Generated by Django 3.2 on 2021-11-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20211103_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchplayer',
            name='award',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='lane',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
